// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBHuXO-9tr5CDi72lWP4bTa7_SWE6JC638',
    appId: '1:639506914253:web:a7442bfb93b1854aac0284',
    messagingSenderId: '639506914253',
    projectId: 'nexthome-b575f',
    authDomain: 'nexthome-b575f.firebaseapp.com',
    storageBucket: 'nexthome-b575f.firebasestorage.app',
    measurementId: 'G-4RVJ3CRFZ4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCrlv47ysnfr2b-vGa6txfFP2Bi5JEoge4',
    appId: '1:639506914253:android:475aaf77af5c780aac0284',
    messagingSenderId: '639506914253',
    projectId: 'nexthome-b575f',
    storageBucket: 'nexthome-b575f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDCOjKrFANFI0OgYibzPIvWlGVbh8VynxI',
    appId: '1:639506914253:ios:4e77af050859c084ac0284',
    messagingSenderId: '639506914253',
    projectId: 'nexthome-b575f',
    storageBucket: 'nexthome-b575f.firebasestorage.app',
    iosBundleId: 'com.example.nextHome',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDCOjKrFANFI0OgYibzPIvWlGVbh8VynxI',
    appId: '1:639506914253:ios:4e77af050859c084ac0284',
    messagingSenderId: '639506914253',
    projectId: 'nexthome-b575f',
    storageBucket: 'nexthome-b575f.firebasestorage.app',
    iosBundleId: 'com.example.nextHome',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBHuXO-9tr5CDi72lWP4bTa7_SWE6JC638',
    appId: '1:639506914253:web:582fe396684d56d5ac0284',
    messagingSenderId: '639506914253',
    projectId: 'nexthome-b575f',
    authDomain: 'nexthome-b575f.firebaseapp.com',
    storageBucket: 'nexthome-b575f.firebasestorage.app',
    measurementId: 'G-NXEGK4HSTQ',
  );

}